"""Curated development set of data analysis questions for prompt optimization."""

from typing import List, Optional
import dspy

SAMPLE_SALES_PREVIEW = """Dataset: sample_sales.csv
Shape: 51 rows, 4 columns
Columns:
- Date (object/string): Transaction date in YYYY-MM-DD format (Jan 2024 to Feb 2024)
- Category (object/string): Product category (Electronics, Clothing, Home & Garden, Books, Sports)
- Units_Sold (int64): Quantity of items sold per transaction (range: 6 to 35)
- Revenue (float64): Total dollar revenue generated from transaction (range: 164.89 to 1999.80)
Sample rows:
  Date        Category       Units_Sold  Revenue
  2024-01-01  Electronics    12          1199.88
  2024-01-02  Clothing       25          624.75
  2024-01-03  Home & Garden  8           399.92
  2024-01-04  Books          15          224.85
  2024-01-05  Sports         10          499.90
"""

DEV_QUESTIONS = [
    {
        "question": "Calculate the total revenue generated by each product category and display an interactive bar chart comparing them.",
        "target_dimension": "Category",
        "target_metric": "Revenue",
        "expected_chart_type": "bar",
        "expected_keywords": ["Electronics", "Clothing", "Revenue", "Total"],
    },
    {
        "question": "Show the daily revenue trend over time across all categories and plot a time-series line chart with date markers.",
        "target_dimension": "Date",
        "target_metric": "Revenue",
        "expected_chart_type": "line",
        "expected_keywords": ["Date", "trend", "daily", "Revenue"],
    },
    {
        "question": "Analyze the relationship between Units_Sold and Revenue across transactions using an interactive scatter plot with a trendline.",
        "target_dimension": "Units_Sold",
        "target_metric": "Revenue",
        "expected_chart_type": "scatter",
        "expected_keywords": ["Units_Sold", "correlation", "Revenue", "scatter"],
    },
    {
        "question": "Analyze the distribution and spread of revenue per transaction across different categories using a box plot.",
        "target_dimension": "Category",
        "target_metric": "Revenue",
        "expected_chart_type": "box",
        "expected_keywords": ["distribution", "box", "median", "spread"],
    },
    {
        "question": "Calculate total units sold by category and create a ranked horizontal bar or donut chart illustrating volume distribution.",
        "target_dimension": "Category",
        "target_metric": "Units_Sold",
        "expected_chart_type": "bar",
        "expected_keywords": ["Units_Sold", "volume", "Category", "rank"],
    },
]


def get_dev_set(
    dataset_path: str = "data/sample_sales.csv",
    preview: Optional[str] = None,
) -> List[dspy.Example]:
    """Build and return curated dev set of DSPy Example objects for prompt optimization.

    Each example is initialized with input keys: 'question' and 'dataset_preview'.
    """
    effective_preview = preview or SAMPLE_SALES_PREVIEW
    examples = []

    for item in DEV_QUESTIONS:
        ex = dspy.Example(
            question=item["question"],
            dataset_preview=effective_preview,
            dataset_path=dataset_path,
            target_dimension=item["target_dimension"],
            target_metric=item["target_metric"],
            expected_chart_type=item["expected_chart_type"],
            expected_keywords=item["expected_keywords"],
        ).with_inputs("question", "dataset_preview")
        examples.append(ex)

    return examples
